databases:
  - name: brew-co-db
    plan: free
    databaseName: brewco
    user: brewco

services:
  - type: web
    name: brew-co-backend
    plan: free
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    dockerCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: brew-co-db
          property: connectionString
      - key: GEMINI_API_KEY
        sync: false
      - key: CHANNEL_STUB_URL
        value: https://brew-co-channel-stub-5k6e.onrender.com
      - key: FRONTEND_URL
        value: https://brewco-crm.vercel.app
      - key: FRONTEND_URLS
        value: https://brewco-crm.vercel.app,https://brew-co-crm-chi.vercel.app
      - key: PORT
        value: 8000

  - type: web
    name: brew-co-channel-stub
    plan: free
    runtime: docker
    dockerfilePath: ./channel-stub/Dockerfile
    dockerContext: ./channel-stub
    dockerCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CRM_URL
        value: https://brew-co-crm-xlin.onrender.com
      - key: PORT
        value: 3003
